### ISSUE TITLE
Error while testing inpaint

### ISSUE THREAD

**Issue by tiberiuichim** [JasonS09/comfy_sd_krita_plugin#22]
**Describe the bug**
I get this error in the ComfyUI terminal:

```
Traceback (most recent call last):
  File "/mnt/docker/work/sd/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/docker/work/sd/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/docker/work/sd/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/docker/work/sd/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/docker/work/sd/ComfyUI/server.py", line 464, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/docker/work/sd/ComfyUI/execution.py", line 596, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'LoadBase64Image'
```

**To Reproduce**

I'm using Krita 5.1, I've selected a layer with a transparency mask, I've clicked "New layer from visible". On this new layer, I've triggered the "start inpaint" button.

**Screenshots**

![image](https://github.com/JasonS09/comfy_sd_krita_plugin/assets/141568/1590deba-b975-4391-8554-40c85a484888)

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu
 - ComfyUI HEAD at f368e5ac7d31649b22c0c1e44bc9fa8002fcb117
 - comfy_sd_krita git clones from today

**Comment by JasonS09** [comment]
Hey! 

Seems you're missing the [required nodes](https://github.com/JasonS09/comfy_sd_krita_plugin_nodes). Did you install them?

**Comment by tiberiuichim** [comment]
Ah... I might have forgotten to restart ComfyUI

**Comment by tiberiuichim** [comment]
That was the problem, inpainting works as expected.
