### ISSUE TITLE
`AssertionError` when running txt2img

### ISSUE THREAD

**Issue by space-nuko** [JasonS09/comfy_sd_krita_plugin#32]
**Describe the bug**
I just installed the plugin, loaded my model and hit `Start txt2img`, then this happens

<details><summary>Details</summary>
<p>

```
AssertionError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Wed Nov  1 16:24:48 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\a\AppData\Roaming\krita\pykrita\krita_comfy\script.py in cb(response=PromptResponse(mode='txt2img', sd_model='...=[Base64Image: PyQt5.QtCore.QSize(512, 512)]))
  313                 except TypeError:
  314                     pass
  315                 assert False, e
  316 
  317             if self.cfg("hide_layers", bool):
e undefined
AssertionError: Raw data size: 1048576, Expected size: 4194304
    __cause__ = None
    __class__ = <class 'AssertionError'>
    __context__ = AssertionError('Raw data size: 1048576, Expected size: 4194304')
    __delattr__ = <method-wrapper '__delattr__' of AssertionError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AssertionError object>
    __doc__ = 'Assertion failed.'
    __eq__ = <method-wrapper '__eq__' of AssertionError object>
    __format__ = <built-in method __format__ of AssertionError object>
    __ge__ = <method-wrapper '__ge__' of AssertionError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AssertionError object>
    __gt__ = <method-wrapper '__gt__' of AssertionError object>
    __hash__ = <method-wrapper '__hash__' of AssertionError object>
    __init__ = <method-wrapper '__init__' of AssertionError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AssertionError object>
    __lt__ = <method-wrapper '__lt__' of AssertionError object>
    __ne__ = <method-wrapper '__ne__' of AssertionError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AssertionError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AssertionError object>
    __repr__ = <method-wrapper '__repr__' of AssertionError object>
    __setattr__ = <method-wrapper '__setattr__' of AssertionError object>
    __setstate__ = <built-in method __setstate__ of AssertionError object>
    __sizeof__ = <built-in method __sizeof__ of AssertionError object>
    __str__ = <method-wrapper '__str__' of AssertionError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = (AssertionError('Raw data size: 1048576, Expected size: 4194304'),)
    with_traceback = <built-in method with_traceback of AssertionError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\krita\pykrita\krita_comfy\script.py", line 306, in cb
    layers = [
  File "C:\Users\a\AppData\Roaming\krita\pykrita\krita_comfy\script.py", line 307, in <listcomp>
    insert(name if name else f"{mode} {i + 1}", output)
  File "C:\Users\a\AppData\Roaming\krita\pykrita\krita_comfy\script.py", line 274, in insert
    assert expected == size, f"Raw data size: {size}, Expected size: {expected}"
AssertionError: Raw data size: 1048576, Expected size: 4194304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\krita\pykrita\krita_comfy\script.py", line 315, in cb
    assert False, e
AssertionError: Raw data size: 1048576, Expected size: 4194304
```

</p>
</details>

However I figured out, if you check `Disable base/max size` or select the canvas then the error stops happening. But it was very confusing since nothing mentions it in the readme

**To Reproduce**
1. Go to `txt2img`
2. Click `Start txt2img`
3. See error

**Desktop (please complete the following information):**
 - OS: Windows
 - WebUI commit revision `9906e3efe31a0fc399262766da33c210fb4e8215`
 - Extension commit revision 43b90b7902720ca8eed65df61c7b5b2e3ddc4e2f

**Additional context**

**Comment by JasonS09** [comment]
Yes, you should always select the canvas before generating an image. Reason:
https://github.com/JasonS09/comfy_sd_krita_plugin/issues/3#issuecomment-1656184249

**Comment by space-nuko** [comment]
Okay maybe best to show a popup in that case instead of throwing an error? Or remove the limitation if it makes more sense?

**Comment by JasonS09** [comment]
> Okay maybe best to show a popup in that case instead of throwing an error? Or remove the limitation if it makes more sense?

Actually someone suggested to automatically select the canvas if not done. I think that's the best way to handle the issue. I'll be working on it, should push the change soon.

**Comment by ElliottLester** [comment]
I thought it was just checking they were the same size but the input/output gets rounded to the nearest 8px.
when there is a  selection we resize can we just always resize to the canvas size? (i didn't look too closely at the code)

**Comment by JasonS09** [comment]
Actually I think I can see the intention of the previous mantainer with this. If we totally removed the requirement then upscaling wouldn't work. It's no longer required for txt2img and img2img after this new push.
